# Generated by Django 6.1.1 on 2026-09-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_type', models.CharField(max_length=100)),
                ('surgery_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('diet_instructions', models.TextField(blank=True)),
                ('activity_restrictions', models.TextField(blank=True)),
                ('wound_care_instructions', models.TextField(blank=True)),
                ('general_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_plans', to='patients.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_plans', to='patients.patient')),
            ],
            options={
                'db_table': 'discharge_plans',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DischargeMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField(default=7)),
                ('instructions', models.TextField(blank=True)),
                ('discharge_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='discharge.dischargeplan')),
            ],
            options={
                'db_table': 'discharge_medications',
            },
        ),
        migrations.CreateModel(
            name='DischargeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('department', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('discharge_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='discharge.dischargeplan')),
            ],
            options={
                'db_table': 'discharge_follow_ups',
            },
        ),
    ]
