# Generated by Django 6.1.1 on 2026-09-24 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargeplan',
            name='authorization_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dischargeplan',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargeplan',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_discharge_plans', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='dischargeplan',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_plans', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='dischargeplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_authorization', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
    ]
