# Generated by Django 6.1.1 on 2026-09-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='reschedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='reschedule_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='reschedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled'), ('reschedule_requested', 'Reschedule Requested'), ('cancelled', 'Cancelled')], default='upcoming', max_length=25),
        ),
    ]
