# Generated by Django 6.1.1 on 2026-09-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pain_level', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('wound_condition', models.CharField(choices=[('normal', 'Normal & Healing'), ('mild_redness', 'Mild Redness'), ('swelling', 'Moderate Swelling'), ('discharge', 'Fluid Discharge'), ('severe', 'Severe Concern')], max_length=20)),
                ('symptoms', models.JSONField(default=list)),
                ('medication_adherence', models.CharField(choices=[('all', 'Took all prescribed doses'), ('some', 'Missed some doses'), ('none', 'Did not take medications')], max_length=10)),
                ('additional_notes', models.TextField(blank=True)),
                ('recovery_score', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_checkins', to='patients.patient')),
            ],
            options={
                'db_table': 'recovery_checkins',
                'ordering': ['-date', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('confidence', models.FloatField()),
                ('contributing_factors', models.JSONField(default=dict)),
                ('recommendation_category', models.CharField(max_length=100)),
                ('doctor_review_notes', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_prediction', to='recovery.recoverycheckin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctor')),
            ],
            options={
                'db_table': 'risk_predictions',
                'ordering': ['-predicted_at'],
            },
        ),
    ]
